name: Deploy

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Cache Expo Dependencies
      uses: actions/cache@v4
      id: expo-cache
      with:
        path: |
          ~/.npm
          ~/node_modules
          ~/.expo
        key: ${{ runner.os }}-expo-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-expo-
        
    - name: Install Dependencies
      if: steps.expo-cache.outputs.cache-hit != 'true'
      run: npm ci
        
    - name: Setup Expo
      uses: expo/expo-github-action@v8
      with:
        expo-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
        packager: npm
        
    - name: Create env file (Production)
      if: github.ref == 'refs/heads/main'
      run: |
        cat > .env << EOL
        FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
        EOL
        
    - name: Build Web (Production)
      if: github.ref == 'refs/heads/main'
      run: |
        set -e
        echo "Installing Expo dependencies..."
        npx expo install --fix
        echo "Building web application..."
        npx expo export:web
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
        
    - name: Deploy to Firebase Hosting (Production)
      if: github.ref == 'refs/heads/main'
      uses: FirebaseExtended/action-hosting-deploy@v0.7.1
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        channelId: live
        projectId: ${{ secrets.FIREBASE_PROJECT_ID }}
        entryPoint: frontend
        
    - name: Create env file (Staging)
      if: github.ref == 'refs/heads/staging'
      run: |
        cat > .env << EOL
        FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY_STAGING }}
        FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN_STAGING }}
        FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
        FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET_STAGING }}
        FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID_STAGING }}
        FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID_STAGING }}
        FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID_STAGING }}
        EOL
        
    - name: Build Web (Staging)
      if: github.ref == 'refs/heads/staging'
      run: |
        set -e
        echo "Installing Expo dependencies..."
        npx expo install --fix
        echo "Building web application..."
        npx expo export:web
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY_STAGING }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN_STAGING }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET_STAGING }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID_STAGING }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID_STAGING }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID_STAGING }}
        
    - name: Deploy to Firebase Hosting (Staging)
      if: github.ref == 'refs/heads/staging'
      uses: FirebaseExtended/action-hosting-deploy@v0.7.1
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}
        channelId: staging
        projectId: ${{ secrets.FIREBASE_PROJECT_ID_STAGING }}
        entryPoint: frontend
        
    - name: Cleanup
      if: always()
      run: |
        rm -f .env
        rm -rf web-build 